import turtle
s = turtle.Screen()
s.bgcolor('white')
pen = turtle.Turtle()
pen.speed(1)
pen.color('yellow')
pen.begin_fill()
pen.fillcolor('purple')
pen.left(140)
pen.forward(180)
pen.circle(-90, 200)
pen.setheading(60)
pen.circle(-90, 200)
pen.forward(180)
pen.end_fill()
pen.hideturtle()
s.mainloop()